# Generated by Django 4.1.5 on 2023-04-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_equipe_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='imagem',
        ),
    ]
