# Generated by Django 4.1.5 on 2023-04-22 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='imagem',
        ),
    ]
