# Generated by Django 4.1.5 on 2023-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cargo_ativo_alter_funcionario_ativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='ativo',
            new_name='atiivo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='ativo',
            new_name='atiivo',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='ativo',
            new_name='atiivo',
        ),
    ]
