# Generated by Django 4.1.5 on 2023-04-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_ativo_cargo_atiivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='atiivo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='atiivo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='atiivo',
        ),
    ]
