# Generated by Django 4.1.5 on 2023-04-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cargo_atiivo_funcionario_atiivo_servico_atiivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='atiivo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='atiivo',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='atiivo',
        ),
    ]
